export const MODULE_ID = "abomination-vaults-expanded";
export const CHANGES_JOURNAL_ID = "UTWz996e1nM1OkQ6";
export const NAMES_TO_ID = {
	// Changes to the Vaults
	"A: Gauntlight Ruins": "Hatf6BjfZlzLxoGl",
	"B: Servants' Quarters": "zaHKCNanpNtKwUlg",
	"B02. Magic Mirror": "surluLUD8HprMYIw",
	"B06. Tiger Painting": "MY61uS4Lk2va9xoZ",
	"B08. Extra Traps": "PATXWXugE62DQT8P",
	"B09. Loyal Dog": "KSCa8Wx2rSKuzHC1",
	"B12. His Other Pet": "CLm67CNpT0gNtor0",
	"B22. Clockwork Hunter": "3prWqGPJfXW7MXX2",
	"C: Library": "89GAwg1joTirFLeP",
	"C11. Volluk's Short Appearance": "yoqNYnbhOoRN3LVs",
	"C36. Descriptions of Natural Phenomena": "i9AefLm995dWceGc",
	"Continuing from Failure": "PHbKpcEroz8eo0L0",
	"D: Belcorra's Retreat": "hWrhuNawYtBHcLir",
	"D4. Empty Wine Bottle": "asJS8eHcOPyFe6uj",
	"D8. Locks & Volluk Changes": "0QvrO5NrcVgpXnQh",
	"D12. The Barrier": "UyMAv9ZHWBmhaIjD",
	"D14. Jaul and Moral Decisions": "sGKQpOOUddDuqHiM",
	"D18. Otari Info": "lk66S7alrffMuN74",
	"E: Arena": "4VEdkVtJbBfCJUob",
	"The Theft Jr.": "9wZ1rzcXylATH3lt",
	"E16. Shrinking Trap": "8HMU29ovFdbH02PM",
	"E23. Under the Mattress": "OaeeTTihjObIDtsv",
	"E26. The Cheery Man & The Red Holiday": "H0HrT2DVDsl99jsh",
	"F: Labs": "hyDibz07F2uqRhZk",
	"F23. Spectral Reflection": "wSI9sQVJOXpIvVZp",
	"F24. Loose Tile": "fwvEtAhF4VmVdcpe",
	"Foreword": "OmLsmbwPtNMw7csF",
	"G: Prison": "EScSkgydRKO4qZPM",
	"G17. Stasis Expanded": "Tty7S474BIN0QB2V",
	"G3. Drill Puzzle": "eyjVczJx1YV9ygxR",
	"G7. Under the Disc": "OPBsOKfHwnQlxdbe",
	"G8. Genderflipped": "Cb2bDOyglBnfnZNA",
	"H: Farm": "Hgpy5vof4fkWkBy0",
	"H17. Broken Lift": "NkSbg4k6YDgt7c1t",
	"H39. Body Mixup": "H50HxEixECs3Tm7f",
	"I: Hunting Grounds": "Yrk1u4tnvH3wr4Hq",
	"I26. Dr. Quagmire I Presume": "UOe5iicUaerB7Eo8",
	"I46. Bottomless Pit": "FEYFCrJHgFHrJVj3",
	"I48. Flumps!": "Lyg4W71yIrmtTbfO",
	"I50. A Puzzle": "Tu30ksiJBQYprptD",
	"I51. Ravirex's Grief": "y8nXL3hatHnG5XZC",
	"J: Temple": "PyteM8RhGjWxXAtt",
	"J16. The Veiled Master": "56ulq98tpQQP3Jup",
	"J20. Belcorra's Changes": "cMTTlG0mnrNoF8rT",
};
